server:
  port: 7070
  compression:
    enabled: true
spring:
  application:
    name: client-a
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true