server:
  port: 8761
eureka:
  instance:
    hostname: localhsot
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defualtZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false